version: "3.9"
services:
  db:
    image: mysql:8.0.26
    container_name: mysql-container
    #    hostname: db-server
    #    volumes:
    #      - type: volume
    #        source: mysql-data
    #        target: /var/lib/mysql
    #        volume:
    #          nocopy: true
    volumes:
      - mysql-data:/var/lib/mysql
      #    restart: always
    cap_add:
      # https://matsuand.github.io/docs.docker.jp.onthefly/engine/security/seccomp/#significant-syscalls-blocked-by-the-default-profile
      - ALL  # CAP_SYS_NICE
    networks:
      # networksの識別子
      - container-link
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django-db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
  web:
    build:
      context: .
      dockerfile: PythonDockerfile
    container_name: django-container
    #    hostname: django-servers
    command: python manage.py runserver 0.0.0.0:8000
    #    volumes:
    #      - .:/code
    volumes:
      - type: bind
        source: .
        target: /code
    ports:
      - "8000:8000"
    depends_on:
      - db
    #    restart: always
    networks:
      # networksの識別子
      - container-link

volumes:
  mysql-data:

networks:
  container-link: